### ISSUE TITLE
web site on phone

### ISSUE THREAD

**Issue by wb9cne** [pantchox/node-red-contrib-pushstaq#4]
I set this up to activate notification on my android phone.  Do I have to keep a web browser up and logged into pushstaw web site constantly on the phone in order for this to work or am I missing something?

**Comment by pantchox** [comment]
You should have an account and be logged in your device browser.

The channel you wish to subscribe to notifications you should click the "Subscribe" button which is located in the channel top right of the channel page.

**Comment by wb9cne** [comment]
ok, thank you
